package application.characterclassreaderservice.bll;

import application.characterclassreaderservice.CharacterClassFromResourceRequest;
import application.characterclassreaderservice.CharacterClassFromResourceResponse;
import application.characterclassreaderservice.bll.bo.CharacterClassBo;
import application.characterclassreaderservice.bll.bo.CharacterClassNameBo;

public interface CharacterClassReaderBusinessLogicConverter {
    CharacterClassNameBo getCharacterClassNameBoFromCharacterClassFromResourceRequest(CharacterClassFromResourceRequest characterClassFromResourceRequest);

    CharacterClassFromResourceResponse getCharacterClassFromResourceResponseFromCharacterClassBo(CharacterClassBo characterClassBo);
}