package domain.characterservice.bll;

import domain.characterservice.*;
import domain.characterservice.bll.bo.*;

public interface CharacterBusinessLogicConverter {
    CharacterAndVisibilityAndPlayerBo getCharacterAndVisibilityAndPlayerBoFromCreateCharacterRequest(CreateCharacterRequest createCharacterRequest);

    NonPlayableCharacterAndVisibilityAndDungeonMasterBo getNonPlayableCharacterAndVisibilityAndDungeonMasterBoFromCreateNonPlayableCharacterRequest(CreateNonPlayableCharacterRequest createNonPlayableCharacterRequest);

    CharacterAndDungeonMasterBo getCharacterAndDungeonMasterBoFromChangeCharacterToNonPlayableCharacterRequest(ChangeCharacterToNonPlayableCharacterRequest changeCharacterToNonPlayableCharacterRequest);

    NonPlayableCharacterAndDungeonMasterBo getNonPlayableCharacterAndDungeonMasterBoFromChangeNonPlayableCharacterToCharacterRequest(ChangeNonPlayableCharacterToCharacterRequest changeNonPlayableCharacterToCharacterRequest);

    CharacterAndPlayerBo getCharacterAndPlayerBoFromUpdatedCharacterRequest(UpdatedCharacterRequest updatedCharacterRequest);

    CreateCharacterResponse getCreateCharacterResponseFromCharacterBo(CharacterBo characterBo);

    CreateNonPlayableCharacterResponse getCreateNonPlayableCharacterResponseFromNonPlayableCharacterBo(NonPlayableCharacterBo nonPlayableCharacterBo);

    ChangeCharacterToNonPlayableCharacterResponse getChangeCharacterToNonPlayableCharacterResponseFromNonPlayableCharacterBo(NonPlayableCharacterBo nonPlayableCharacterBo);

    ChangeNonPlayableCharacterToCharacterResponse getChangeNonPlayableCharacterToCharacterResponseFromCharacterBo(CharacterBo characterBo);

    UpdatedCharacterResponse getUpdatedCharacterResponseFromCharacterBo(CharacterAndVisibilityBo characterAndVisibilityBo);

    ChangeVisibilityOfCharacterDetailsResponse getChangeVisibilityOfCharacterDetailsResponseFromCharacterAndVisibilityBo(CharacterAndVisibilityBo characterAndVisibilityBo);

    CharacterAndVisibilityAndPlayerBo getCharacterAndVisibilityAndPlayerBoFromChangeVisibilityOfCharacterDetailsRequest(ChangeVisibilityOfCharacterDetailsRequest changeVisibilityOfUpdatedCharacterRequest);

    CharacterAndVisibilityBo getCharacterAndVisibilityBoFromCharacterAndVisibilityAndPlayerBo(CharacterAndVisibilityAndPlayerBo characterAndVisibilityAndPlayerBo);
}