package services.resultservice.bll;

import services.resultservice.ChangeVisibilityOfResultDetailsRequest;
import services.resultservice.ChangeVisibilityOfResultDetailsResponse;
import services.resultservice.UpdatedResultRequest;
import services.resultservice.UpdatedResultResponse;
import services.resultservice.bll.bo.ResultAndPlayerBo;
import services.resultservice.bll.bo.ResultAndVisibilityAndPlayerBo;
import services.resultservice.bll.bo.ResultAndVisibilityBo;

public interface ResultBusinessLogicConverter {
    ResultAndPlayerBo getResultAndPlayerBoFromUpdatedResultRequest(UpdatedResultRequest updatedResultRequest);

    ResultAndVisibilityAndPlayerBo getResultAndVisibilityAndPlayerBoFromChangeVisibilityOfResultDetailsRequest(ChangeVisibilityOfResultDetailsRequest changeVisibilityOfUpdatedResultRequest);

    UpdatedResultResponse getUpdatedResultResponseFromResultAndVisibilityBo(ResultAndVisibilityBo resultAndVisibilityBo);

    ChangeVisibilityOfResultDetailsResponse getChangeVisibilityOfResultDetailsResponseFromResultAndVisibilityBo(ResultAndVisibilityBo resultAndVisibilityBo);

    ResultAndVisibilityBo getResultAndVisibilityBoFromResultAndVisibilityAndPlayerBo(ResultAndVisibilityAndPlayerBo resultAndVisibilityAndPlayerBo);
}