package services.characterservice.bll;

import services.characterservice.*;
import services.characterservice.bll.bo.*;

public interface CharacterBusinessLogicConverter {
    CharacterAndVisibilityAndPlayerBo getCharacterAndVisibilityAndPlayerBoFromCreateCharacterRequest(CreateCharacterRequest createCharacterRequest);

    NonPlayableCharacterAndVisibilityAndDungeonMasterBo getNonPlayableCharacterAndVisibilityAndDungeonMasterBoFromCreateNonPlayableCharacterRequest(CreateNonPlayableCharacterRequest createNonPlayableCharacterRequest);

    CharacterAndDungeonMasterBo getCharacterAndDungeonMasterBoFromChangeCharacterToNonPlayableCharacterRequest(ChangeCharacterToNonPlayableCharacterRequest changeCharacterToNonPlayableCharacterRequest);

    CreateCharacterResponse getCreateCharacterResponseFromCharacterBo(CharacterBo characterBo);

    CreateNonPlayableCharacterResponse getCreateNonPlayableCharacterResponseFromNonPlayableCharacterBo(NonPlayableCharacterBo nonPlayableCharacterBo);

    ChangeCharacterToNonPlayableCharacterResponse getChangeCharacterToNonPlayableCharacterResponseFromNonPlayableCharacterBo(NonPlayableCharacterBo nonPlayableCharacterBo);
}