package services.resultdetailservice.bll;

import services.resultdetailservice.bll.bo.ResultAndPlayerBo;
import services.resultdetailservice.bll.bo.ResultDetailsAndVisibilityAndPlayerBo;
import services.resultdetailservice.bll.bo.ResultDetailsAndVisibilityBo;

public interface ResultDetailBusinessLogic {
    ResultDetailsAndVisibilityBo getResultDetailsAndVisibilityBo(ResultAndPlayerBo resultAndPlayerBo);

    ResultDetailsAndVisibilityBo getResultDetailsAndVisibilityBo(ResultDetailsAndVisibilityAndPlayerBo resultDetailsAndVisibilityAndPlayerBo);
}