package services.campaigndetailservice.bll;

import services.campaigndetailservice.CampaignDetailsRequest;
import services.campaigndetailservice.CampaignDetailsResponse;
import services.campaigndetailservice.CampaignDetailsVisibilityRequest;
import services.campaigndetailservice.CampaignDetailsVisibilityResponse;
import services.campaigndetailservice.bll.bo.CampaignAndPlayerBo;
import services.campaigndetailservice.bll.bo.CampaignDetailsAndVisibilityAndDungeonMasterBo;
import services.campaigndetailservice.bll.bo.CampaignDetailsAndVisibilityBo;

public interface CampaignDetailBusinessLogicConverter {
    CampaignAndPlayerBo getCampaignAndPlayerBoFromCampaignDetailsRequest(CampaignDetailsRequest campaignDetailsRequest);

    CampaignDetailsAndVisibilityAndDungeonMasterBo getCampaignDetailsAndVisibilityAndDungeonMasterBoFromCampaignDetailsVisibilityRequest(CampaignDetailsVisibilityRequest campaignDetailsVisibilityRequest);

    CampaignDetailsResponse getCampaignDetailsResponseFromCampaignDetailsAndVisibilityBo(CampaignDetailsAndVisibilityBo campaignDetailsAndVisibilityBo);

    CampaignDetailsVisibilityResponse getCampaignDetailsVisibilityResponseFromCampaignDetailsAndVisibilityBo(CampaignDetailsAndVisibilityBo campaignDetailsAndVisibilityBo);

    CampaignDetailsAndVisibilityBo getCampaignDetailsAndVisibilityBoFromCampaignDetailsAndVisibilityAndDungeonMasterBo(CampaignDetailsAndVisibilityAndDungeonMasterBo campaignDetailsAndVisibilityAndDungeonMasterBo);
}