package services.campaigndetailservice.bll;

import services.campaigndetailservice.*;
import services.campaigndetailservice.bll.bo.*;

public interface CampaignDetailBusinessLogicConverter {
    CampaignAndPlayerBo getCampaignAndPlayerBoFromCampaignDetailsRequest(CampaignDetailsRequest campaignDetailsRequest);

    CampaignDetailsAndVisibilityAndDungeonMasterBo getCampaignDetailsAndVisibilityAndDungeonMasterBoFromCampaignDetailsVisibilityRequest(CampaignDetailsVisibilityRequest campaignDetailsVisibilityRequest);

    CampaignAndPlayerAndDungeonMasterBo getCampaignAndPlayerAndDungeonMasterBoFromAddPlayerToCampaignRequest(AddPlayerToCampaignRequest addPlayerToCampaignRequest);

    CampaignDetailsResponse getCampaignDetailsResponseFromCampaignDetailsAndVisibilityBo(CampaignDetailsAndVisibilityBo campaignDetailsAndVisibilityBo);

    CampaignDetailsVisibilityResponse getCampaignDetailsVisibilityResponseFromCampaignDetailsAndVisibilityBo(CampaignDetailsAndVisibilityBo campaignDetailsAndVisibilityBo);

    AddPlayerToCampaignResponse getAddPlayerToCampaignResponseFromCampaignDetailsBo(CampaignDetailsBo campaignDetailsBo);

    CampaignDetailsAndVisibilityBo getCampaignDetailsAndVisibilityBoFromCampaignDetailsAndVisibilityAndDungeonMasterBo(CampaignDetailsAndVisibilityAndDungeonMasterBo campaignDetailsAndVisibilityAndDungeonMasterBo);
}