package services.campaigndetailservice.bll;

import services.campaigndetailservice.bll.bo.*;

public interface CampaignDetailBusinessLogic {
    CampaignDetailsAndVisibilityBo getCampaignDetailsAndVisibilityBo(CampaignAndPlayerBo campaignAndPlayerBo);

    CampaignDetailsAndVisibilityBo getCampaignDetailsAndVisibilityBo(CampaignDetailsAndVisibilityAndDungeonMasterBo campaignDetailsAndVisibilityAndDungeonMasterBo);

    CampaignDetailsBo getCampaignDetailsBo(CampaignAndPlayerAndDungeonMasterBo campaignAndPlayerAndDungeonMasterBo);
}