package services.locationdetailservice.bll;

import services.locationdetailservice.LocationDetailsRequest;
import services.locationdetailservice.LocationDetailsResponse;
import services.locationdetailservice.LocationDetailsVisibilityRequest;
import services.locationdetailservice.LocationDetailsVisibilityResponse;
import services.locationdetailservice.bll.bo.LocationAndPlayerBo;
import services.locationdetailservice.bll.bo.LocationDetailsAndVisibilityAndPlayerBo;
import services.locationdetailservice.bll.bo.LocationDetailsAndVisibilityBo;

public interface LocationDetailBusinessLogicConverter {
    LocationAndPlayerBo getLocationAndPlayerBoFromLocationDetailsRequest(LocationDetailsRequest locationDetailsRequest);

    LocationDetailsAndVisibilityAndPlayerBo getLocationDetailsAndVisibilityAndPlayerBoFromLocationDetailsVisibilityRequest(LocationDetailsVisibilityRequest locationDetailsVisibilityRequest);

    LocationDetailsResponse getLocationDetailsResponseFromLocationDetailsAndVisibilityBo(LocationDetailsAndVisibilityBo locationDetailsAndVisibilityBo);

    LocationDetailsVisibilityResponse getLocationDetailsVisibilityResponseFromLocationDetailsAndVisibilityBo(LocationDetailsAndVisibilityBo locationDetailsAndVisibilityBo);

    LocationDetailsAndVisibilityBo getLocationDetailsAndVisibilityBoFromLocationDetailsAndVisibilityAndPlayerBo(LocationDetailsAndVisibilityAndPlayerBo locationDetailsAndVisibilityAndPlayerBo);
}