package services.locationdetailservice;

import com.google.inject.Inject;
import services.locationdetailservice.bll.LocationDetailBusinessLogic;
import services.locationdetailservice.bll.LocationDetailBusinessLogicConverter;
import services.locationdetailservice.bll.bo.LocationDetailsAndVisibilityAndDungeonMasterBo;
import services.locationdetailservice.bll.bo.LocationDetailsAndVisibilityBo;

public class UpdateLocationDetailsVisibilityImpl implements UpdateLocationDetailsVisibility {
    @Inject
    private LocationDetailBusinessLogicConverter locationDetailBusinessLogicConverter;
    @Inject
    private LocationDetailBusinessLogic locationDetailBusinessLogic;

    public LocationDetailsVisibilityResponse getLocationDetailsVisibilityResponse(LocationDetailsVisibilityRequest locationDetailsVisibilityRequest) {
        LocationDetailsAndVisibilityAndDungeonMasterBo locationDetailsAndVisibilityAndDungeonMasterBo = locationDetailBusinessLogicConverter.getLocationDetailsAndVisibilityAndDungeonMasterBoFromLocationDetailsVisibilityRequest(locationDetailsVisibilityRequest);
        LocationDetailsAndVisibilityBo locationDetailsAndVisibilityBo = locationDetailBusinessLogic.getLocationDetailsAndVisibilityBo(locationDetailsAndVisibilityAndDungeonMasterBo);
        return locationDetailBusinessLogicConverter.getLocationDetailsVisibilityResponseFromLocationDetailsAndVisibilityBo(locationDetailsAndVisibilityBo);
    }
}