package com.ebgolden.domain.locationservice.bll;

import com.ebgolden.domain.locationservice.UpdatedLocationRequest;
import com.ebgolden.domain.locationservice.UpdatedLocationResponse;
import com.ebgolden.domain.locationservice.ChangeVisibilityOfLocationDetailsRequest;
import com.ebgolden.domain.locationservice.ChangeVisibilityOfLocationDetailsResponse;
import com.ebgolden.domain.locationservice.bll.bo.LocationAndPlayerBo;
import com.ebgolden.domain.locationservice.bll.bo.LocationAndVisibilityAndDungeonMasterBo;
import com.ebgolden.domain.locationservice.bll.bo.LocationAndVisibilityBo;

public interface LocationBusinessLogicConverter {
    LocationAndPlayerBo getLocationAndPlayerBoFromUpdatedLocationRequest(UpdatedLocationRequest updatedLocationRequest);

    LocationAndVisibilityAndDungeonMasterBo getLocationAndVisibilityAndDungeonMasterBoFromChangeVisibilityOfLocationDetailsRequest(ChangeVisibilityOfLocationDetailsRequest changeVisibilityOfUpdatedLocationRequest);

    UpdatedLocationResponse getUpdatedLocationResponseFromLocationAndVisibilityBo(LocationAndVisibilityBo locationAndVisibilityBo);

    ChangeVisibilityOfLocationDetailsResponse getChangeVisibilityOfLocationDetailsResponseFromLocationAndVisibilityBo(LocationAndVisibilityBo locationAndVisibilityBo);

    LocationAndVisibilityBo getLocationAndVisibilityBoFromLocationAndVisibilityAndDungeonMasterBo(LocationAndVisibilityAndDungeonMasterBo locationAndVisibilityAndDungeonMasterBo);
}