package services.characterdetailservice.bll;

import services.characterdetailservice.bll.bo.CharacterAndPlayerBo;
import services.characterdetailservice.bll.bo.CharacterDetailsAndVisibilityAndPlayerBo;
import services.characterdetailservice.bll.bo.CharacterDetailsAndVisibilityBo;

public interface CharacterDetailBusinessLogic {
    CharacterDetailsAndVisibilityBo getCharacterDetailsAndVisibilityBo(CharacterAndPlayerBo characterAndPlayerBo);

    CharacterDetailsAndVisibilityBo getCharacterDetailsAndVisibilityBo(CharacterDetailsAndVisibilityAndPlayerBo characterDetailsAndVisibilityAndPlayerBo);
}