package services.characterdetailservice.bll;

import services.characterdetailservice.CharacterDetailsRequest;
import services.characterdetailservice.CharacterDetailsResponse;
import services.characterdetailservice.CharacterDetailsVisibilityRequest;
import services.characterdetailservice.CharacterDetailsVisibilityResponse;
import services.characterdetailservice.bll.bo.CharacterAndPlayerBo;
import services.characterdetailservice.bll.bo.CharacterDetailsAndVisibilityAndPlayerBo;
import services.characterdetailservice.bll.bo.CharacterDetailsAndVisibilityBo;

public interface CharacterDetailBusinessLogicConverter {
    CharacterAndPlayerBo getCharacterAndPlayerBoFromCharacterDetailsRequest(CharacterDetailsRequest characterDetailsRequest);

    CharacterDetailsResponse getCharacterDetailsResponseFromCharacterDetailsBo(CharacterDetailsAndVisibilityBo characterDetailsAndVisibilityBo);

    CharacterDetailsVisibilityResponse getCharacterDetailsVisibilityResponseFromCharacterDetailsBo(CharacterDetailsAndVisibilityBo characterDetailsAndVisibilityBo);

    CharacterDetailsAndVisibilityAndPlayerBo getCharacterDetailsAndVisibilityAndPlayerBoFromCharacterDetailsVisibilityRequest(CharacterDetailsVisibilityRequest characterDetailsVisibilityRequest);

    CharacterDetailsAndVisibilityBo getCharacterDetailsAndVisibilityBoFromCharacterDetailsAndVisibilityAndPlayerBo(CharacterDetailsAndVisibilityAndPlayerBo characterDetailsAndVisibilityAndPlayerBo);
}