package services.spellservice.bll;

import services.spellservice.ChangeVisibilityOfSpellDetailsRequest;
import services.spellservice.UpdatedSpellRequest;
import services.spellservice.UpdatedSpellResponse;
import services.spellservice.ChangeVisibilityOfSpellDetailsResponse;
import services.spellservice.bll.bo.SpellAndPlayerBo;
import services.spellservice.bll.bo.SpellAndVisibilityAndPlayerBo;
import services.spellservice.bll.bo.SpellAndVisibilityBo;

public interface SpellBusinessLogicConverter {
    SpellAndPlayerBo getSpellAndPlayerBoFromUpdatedSpellRequest(UpdatedSpellRequest updatedSpellRequest);

    SpellAndVisibilityAndPlayerBo getSpellAndVisibilityAndPlayerBoFromChangeVisibilityOfSpellDetailsRequest(ChangeVisibilityOfSpellDetailsRequest changeVisibilityOfUpdatedSpellRequest);

    UpdatedSpellResponse getUpdatedSpellResponseFromSpellAndVisibilityBo(SpellAndVisibilityBo spellAndVisibilityBo);

    ChangeVisibilityOfSpellDetailsResponse getChangeVisibilityOfSpellDetailsResponseFromSpellAndVisibilityBo(SpellAndVisibilityBo spellAndVisibilityBo);

    SpellAndVisibilityBo getSpellAndVisibilityBoFromSpellAndVisibilityAndPlayerBo(SpellAndVisibilityAndPlayerBo spellAndVisibilityAndPlayerBo);
}