package com.ebgolden.domain.characterclassservice.bll;

import com.ebgolden.domain.characterclassservice.UpdatedCharacterClassRequest;
import com.ebgolden.domain.characterclassservice.UpdatedCharacterClassResponse;
import com.ebgolden.domain.characterclassservice.bll.bo.CharacterClassBo;

public interface CharacterClassBusinessLogicConverter {
    CharacterClassBo getCharacterClassBoFromUpdatedCharacterClassRequest(UpdatedCharacterClassRequest updatedCharacterClassRequest);

    UpdatedCharacterClassResponse getUpdatedCharacterClassResponseFromCharacterClassBo(CharacterClassBo characterClassBo);
}